version: '3'

services:
  fin-serving-layer:
    build:
      context: ./services/fin-serving-layer
      dockerfile: Dockerfile
      args:
        SERVICE_PORT: ${FIN_SERVING_LAYER_PORT}
    ports:
      - "${FIN_SERVING_LAYER_PORT}:${FIN_SERVING_LAYER_PORT}"
    environment:
      - ENV=${ENV}
      - SERVICE_HOST=${FIN_SERVING_LAYER_HOST}
      - SERVICE_PORT=${FIN_SERVING_LAYER_PORT}
      - PLAID_CLIENT_ID=${PLAID_CLIENT_ID}
      - PLAID_SECRET=${PLAID_SECRET}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}

  web:
    build:
      context: ./ui/web
      dockerfile: Dockerfile
      args:
        PORT: ${WEB_UI_PORT}
    ports:
      - "${WEB_UI_PORT}:${WEB_UI_PORT}"
    environment:
      - PORT=${WEB_UI_PORT}
      - REACT_APP_ENV=${ENV}
      - REACT_APP_FIN_SERVING_LAYER_HOST=${FIN_SERVING_LAYER_HOST}
      - REACT_APP_FIN_SERVING_LAYER_PORT=${FIN_SERVING_LAYER_PORT}
      - REACT_APP_FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - REACT_APP_FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
    depends_on:
      - fin-serving-layer
